### ISSUE TITLE
Add new translations

### ISSUE THREAD

**Issue by lsubel** [lsubel/amam#11]
Suggested: Spanish, Portugese, French, Italian

**Comment by pp-jc** [comment]
Hello, 
Is the project still alive ? I would like to contribute to add new translations (to French mostly).

**Comment by lsubel** [comment]
Hey @pp-jc,
of course! I'm currently busy with a study related project, but once it is finished I'm going to add more features to the application! I'd be happy to receive translations. Do you need some kind of guide to set up a translation file?

**Comment by Panphico** [comment]
No, I think I have understand how it works, for each set of questions, there is .ln file per language and in the languages.txt I add the language I just translated.

**Comment by lsubel** [comment]
Alright thank you very much! :)
Also feel free to translate the UI strings s.t. the application can be navigated by french users.

**Comment by Panphico** [comment]
Ok, I'll start there :)

**Comment by lsubel** [comment]
Dutch and french were added as additional translations.
