### ISSUE TITLE
Create better application icon

### ISSUE THREAD

**Issue by lsubel** [lsubel/amam#15]
The icon itself should be svg.

**Comment by PanderMusubi** [comment]
You can use https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by lsubel** [comment]
I have created a new icon [(see here)](https://github.com/lsubel/amam/blob/phonegap/icon.png) a few days ago. However, the uploaded .svg version seem to be buggy. I will investigate it in the evening before closing the ticket.

**Comment by lsubel** [comment]
Apparently the Inkscape produced svg file is invalid due to misplaced clipPath children. However, the svg file is still modifiable in Inkscape 0.91 and just used to generate the png icons. Therefore, this issue gets closed.
