### ISSUE TITLE
Suggestion: add descriptions to questionnaires

### ISSUE THREAD

**Issue by aberlin** [lsubel/amam#57]
A short and a long description of the questionnaires could be useful. It would enable to give a short introduction or overview. As simplest implementation this could show up right before the first question.

**Comment by lsubel** [comment]
I like the idea of a description. I'd suggest that the text is printed right below the select tag s.t. the user can directly make a decision.

**Comment by lsubel** [comment]
Seems to work pretty good! Thanks for the suggestion!
