### ISSUE TITLE
Add an online translation service

### ISSUE THREAD

**Issue by aberlin** [lsubel/amam#64]
An online translation service could be very handy. It would also give non programmers a way to contribute [see also this discussion](https://github.com/LukeStonehm/LogicalDefence/issues/28)

**Comment by lsubel** [comment]
I will take a look into these type of tools once I have some more time. Meanwhile manual translation work is the way to go.

**Comment by lsubel** [comment]
The suggested online translation service works with native Android applications or other pre-specified language translation mechanism. However, AMAM has a custom implementation and data structure for that purpose.
