### ISSUE TITLE
Add authorship of questionnaires

### ISSUE THREAD

**Issue by lsubel** [lsubel/amam#69]
There should be the possibility to attribute authors for their submitted questionnaires. The attribution should be optional and could contain
- Nickname
- Link to Github profile

**Comment by lsubel** [comment]
@aberlin I have added basic authorship contribution note in the application. Do you want to get attributed for your submitted questionnaires?

**Comment by aberlin** [comment]
Yes, this would be nice

**Comment by lsubel** [comment]
Attribution was added.
