### ISSUE TITLE
Suggestion: add random or sequenced flag to questionnaires

### ISSUE THREAD

**Issue by aberlin** [lsubel/amam#76]
For some questionnaires it could make a significant difference if you ask the questions sequenced or random (https://en.m.wikipedia.org/wiki/Questionnaire_construction).  An option menue could be Irritating for the user so an option in the dataset should be enough

**Comment by aberlin** [comment]
I should mention, that some of my questions are heavily inspired by this droid app app.https://github.com/hackathoner/LoveGame I wondered if I accidentally copy pasted something. Obviously I didn't because the original app is English and my contributions where German. Anyway we could adopt this app because it seems to be no longer maintained

**Comment by lsubel** [comment]
I generallly like the idea of multiple question selection methods, however I am wondering about the resulting questionnaire and how it tells something about the character of the person who answers them. 
Regarding the mentioned application I saw that there is a [reserach paper](http://psp.sagepub.com/content/23/4/363.full.pdf+html) were the questions were used for a study of interpersonal closeness. I'd guess that the questions are usable as long as we add citation to the original paper.
This paragraph might also be relevant for #34.
