### ISSUE TITLE
Duplicate questions in Proust questionnaire ?

### ISSUE THREAD

**Issue by Panphico** [lsubel/amam#87]
Hello,
In Proust questionnaire, questions 2 and 19, 4 and 20, 15 and 21, 9 and 25, 7 and 27 are similar or relatively similar. I looked up on the internet and these duplicate are not part of the Proust questionnaires I've found.
Is it done on purpose ?

**Comment by lsubel** [comment]
I guess we have different resource :-)
I used an slightly extended version of the proust question origin from an german [blog](https://durchleser.wordpress.com/marcel-proust/marcel-proust-fragebogen/).
But you are right, these questions are too similar. 
@Panphico Can you hint me to a better version of the Proust questionnaires which could be included?

**Comment by Panphico** [comment]
There is multiple versions of the Proust questionnaire on Internet. I just check multiple sources to find the questions that seems similar to me and deleted in the French translations the one I did not found on these sources. 
I checked on Wikipedia and on other websites : https://en.wikipedia.org/wiki/Proust_Questionnaire

**Comment by lsubel** [comment]
Oh i just noticed. That might be a problem. The assumption of the translation files is that each entry has the same meaning independently from the translation, meaning that e.g. pad.question-15 in german is the same as in english. The idea is that in case of flawed translations, users can change languages to help them understand the question.
I'll remove the duplicated questions from english and german translation. Could you re-align the french translation to the other questionnaires before?

**Comment by Panphico** [comment]
Ok, I'll do it next week :)

**Comment by Panphico** [comment]
Done :)
Please check the pull request and tell me if it suits you.

**Comment by lsubel** [comment]
Awesome, thank you very much! :-)
I will solve some issues and push a new version soon.
